#!/usr/bin/env python3
import json
import os
import argparse
import sys
import shutil
import subprocess
import time
import uuid
from math import ceil
from collections import Counter
try:
    from tqdm import tqdm
except ImportError:
    def tqdm(total=None, unit="it", desc=""):
        class MockTqdm:
            def __init__(self, total): self.n = 0
            def update(self, n=1): self.n += n
            def __enter__(self): return self
            def __exit__(self, *args): pass
        return MockTqdm(total)

# ==========================================
# Shared Utilities
# ==========================================

def load_jsonl(filepath):
    data = {}
    if not os.path.exists(filepath):
        return data
    with open(filepath, 'r') as f:
        for line in f:
            if line.strip():
                try:
                    item = json.loads(line)
                    # Handle list wrapper [ { ... } ] which might be generated by some workers incorrectly
                    if isinstance(item, list) and len(item) > 0 and isinstance(item[0], dict):
                        item = item[0]
                        
                    if isinstance(item, dict) and 'uuid' in item:
                        data[item['uuid']] = item
                except json.JSONDecodeError:
                    pass
    return data

def normalize_instance(instance):
    if isinstance(instance, str):
        return {instance.strip()}
    elif isinstance(instance, list):
        return {i.strip() for i in instance}
    return set()

def run_distributed_logic(input_file, output_file, workers, log_dir, random_sample=0, seed=42):
    """Core distributed runner logic"""
    # Generate a unique session ID
    session_id = uuid.uuid4().hex[:8]
    tmp_dir = os.path.join("tmp", session_id)
    
    # Create subdirectories for better organization
    tmp_input_dir = os.path.join(tmp_dir, "input")
    tmp_output_dir = os.path.join(tmp_dir, "output")
    tmp_log_dir = os.path.join(tmp_dir, "log")
    
    os.makedirs(tmp_input_dir, exist_ok=True)
    os.makedirs(tmp_output_dir, exist_ok=True)
    os.makedirs(tmp_log_dir, exist_ok=True)
    
    if not os.path.exists(input_file):
        print(f"Error: Input file {input_file} not found.")
        return False

    with open(input_file, 'r') as f:
        data = json.load(f)
    
    # Global Random Sampling
    if random_sample > 0 and random_sample < len(data):
        import random
        random.seed(seed)
        print(f"Randomly sampling {random_sample} items from {len(data)} total items (Seed: {seed}).")
        data = random.sample(data, random_sample)

    total_items = len(data)
    if total_items == 0:
        print("Input file is empty.")
        return True

    if workers > total_items:
        workers = total_items
        
    chunk_size = ceil(total_items / workers)
    
    print(f"Running distributed session: {session_id}")
    print(f"Items: {total_items}, Workers: {workers}")
    
    processes = []
    temp_files = []
    
    os.makedirs(os.path.dirname(os.path.abspath(output_file)), exist_ok=True)

    # Split and Launch
    for i in range(workers):
        start_idx = i * chunk_size
        end_idx = min((i + 1) * chunk_size, total_items)
        
        if start_idx >= total_items:
            break
            
        chunk_data = data[start_idx:end_idx]
        
        temp_input = os.path.join(tmp_input_dir, f"temp_input_{i}.json")
        temp_output = os.path.join(tmp_output_dir, f"temp_output_{i}.jsonl")
        worker_log = os.path.join(tmp_log_dir, f"worker_{i}.log")
        
        temp_files.append({
            "input": temp_input,
            "output": temp_output,
            "worker_log": worker_log
        })
        
        with open(temp_input, 'w') as f:
            json.dump(chunk_data, f, indent=2, ensure_ascii=False)
            
        cmd = [
            sys.executable, "main.py",
            "--batch",
            "--input", temp_input,
            "--output", temp_output,
            "--log-dir", log_dir
        ]
        
        with open(worker_log, "w") as log_f:
            p = subprocess.Popen(cmd, stdout=log_f, stderr=subprocess.STDOUT)
            processes.append(p)
    
    # Monitor Loop
    try:
        with tqdm(total=total_items, unit="case", desc="Progress") as pbar:
            while True:
                running = [p.poll() is None for p in processes]
                
                total_processed_count = 0
                for temp in temp_files:
                    out_file = temp["output"]
                    if os.path.exists(out_file):
                        try:
                            with open(out_file, 'rb') as f:
                                total_processed_count += sum(1 for _ in f)
                        except Exception:
                            pass
                
                if total_processed_count > pbar.n:
                    pbar.update(total_processed_count - pbar.n)
                
                if not any(running):
                    break
                
                time.sleep(1)
            
    except KeyboardInterrupt:
        print("\nStopping all processes...")
        for p in processes:
            p.terminate()
        # Fall through to merge results so we can save partial progress
        print("Saving partial results...")

    # Merge Results
    with open(output_file, 'w') as outfile:
        for temp in temp_files:
            t_out = temp["output"]
            if os.path.exists(t_out):
                with open(t_out, 'r') as infile:
                    for line in infile:
                        outfile.write(line)

    # Cleanup
    try:
        shutil.rmtree(tmp_dir)
    except Exception:
        pass
        
    return True

def calculate_accuracy(predictions, gt_map):
    if not gt_map: return 0.0, 0, 0
    correct = 0
    total = 0
    for uid, item in predictions.items():
        if uid in gt_map:
            total += 1
            gt_inst = normalize_instance(gt_map[uid].get('instance', ''))
            pred = item.get('component', '').strip()
            if pred in gt_inst:
                correct += 1
    return (correct / total if total > 0 else 0.0), correct, total

VALID_COMPONENTS = {
    "adservice", "adservice-0", "adservice-1", "adservice-2",
    "aiops-k8s-01", "aiops-k8s-03", "aiops-k8s-04", "aiops-k8s-05", "aiops-k8s-06", "aiops-k8s-07", "aiops-k8s-08",
    "cartservice", "cartservice-1",
    "checkoutservice", "checkoutservice-0", "checkoutservice-1", "checkoutservice-2",
    "currencyservice", "currencyservice-1", "currencyservice-2",
    "emailservice", "emailservice-2",
    "frontend",
    "paymentservice", "paymentservice-0", "paymentservice-1", "paymentservice-2",
    "productcatalogservice", "productcatalogservice-0", "productcatalogservice-2",
    "recommendationservice",
    "redis-cart", "redis-cart-0",
    "shippingservice", "shippingservice-0", "shippingservice-1", "shippingservice-2",
    "tidb-pd", "tidb-pd-0",
    "tidb-tidb", "tidb-tidb-0",
    "tidb-tikv", "tidb-tikv-0"
}

def scan_for_errors(result_file, input_file, gt_map=None):
    """Scans result file for errors and returns lists of failed cases"""
    if not os.path.exists(result_file):
        return [], [], {}
        
    input_map = {}
    with open(input_file, 'r') as f:
        for item in json.load(f):
            if 'uuid' in item:
                input_map[item['uuid']] = item
                
    results = load_jsonl(result_file)
    format_errors = []
    wrong_answers = []
    stats = {"missing": 0, "format": 0, "wrong": 0}
    
    # Check for missing UUIDs
    for uuid, case in input_map.items():
        if uuid not in results:
            format_errors.append(case)
            stats["missing"] += 1
            continue
            
        res = results[uuid]
        comp = str(res.get('component', '')).strip()
        reason = str(res.get('reason', '')).strip()
        
        # 1. Format Check
        is_format_error = False
        if not comp or comp.upper() == "TODO" or comp == "":
            is_format_error = True
        elif not reason or reason.strip().upper() == "TODO":
            is_format_error = True
            
        if is_format_error:
            format_errors.append(case)
            stats["format"] += 1
            continue

        # 2. Validity & Oracle Check
        # Invalid component is treated as Wrong Answer (to be handled in Rounds)
        if comp not in VALID_COMPONENTS:
            wrong_answers.append(case)
            stats["wrong"] += 1
            continue

        # Oracle Check (if GT available)
        if gt_map and uuid in gt_map:
            gt_inst = normalize_instance(gt_map[uuid].get('instance', ''))
            if comp not in gt_inst:
                wrong_answers.append(case)
                stats["wrong"] += 1
            
    return format_errors, wrong_answers, stats

def clean_logs(log_dir, cases):
    """Clean up logs for failed cases before retry"""
    if not os.path.exists(log_dir):
        return
    
    count = 0
    for case in cases:
        if 'uuid' in case:
            uid = case['uuid']
            # Handle directory based logs (logs/uuid/)
            log_path = os.path.join(log_dir, uid)
            if os.path.exists(log_path):
                try:
                    if os.path.isdir(log_path):
                        shutil.rmtree(log_path)
                    else:
                        os.remove(log_path)
                    count += 1
                except OSError:
                    pass
            
            # Handle file based logs (logs/uuid.log) - legacy support
            log_file = os.path.join(log_dir, f"{uid}.log")
            if os.path.exists(log_file):
                try:
                    os.remove(log_file)
                    count += 1
                except OSError:
                    pass
                    
    if count > 0:
        print(f"Cleaned up {count} logs for failed cases.")

# ==========================================
# Commands
# ==========================================

def cmd_run(args):
    """Smart Run: Run -> Scan -> Retry -> Finalize"""
    print("Starting Running...")
    
    # Load GT if provided
    gt_map = {}
    if args.groundtruth:
        if os.path.exists(args.groundtruth):
            with open(args.groundtruth, 'r') as f:
                # Handle both json list and jsonl
                try:
                    content = f.read().strip()
                    if content.startswith('['):
                        for x in json.loads(content):
                            if 'uuid' in x: gt_map[x['uuid']] = x
                    else:
                        for line in content.split('\n'):
                            if line.strip():
                                x = json.loads(line)
                                if 'uuid' in x: gt_map[x['uuid']] = x
                except:
                    pass
        else:
            print(f"Warning: Ground truth file {args.groundtruth} not found.")

    # 0. Setup
    final_output = args.output
    temp_run_output = final_output + ".temp"
    log_dir = args.log_dir
    
    if not args.resume and os.path.exists(log_dir):
        shutil.rmtree(log_dir)
    os.makedirs(log_dir, exist_ok=True)
    
    current_input = args.input
    
    # Handle Random Sampling explicitly here so scan_for_errors knows the correct input scope
    if args.random > 0:
        import random
        random.seed(args.seed)
        with open(args.input, 'r') as f:
            all_data = json.load(f)
        
        if args.random < len(all_data):
            print(f"Randomly sampling {args.random} items from {len(all_data)} total items (Seed: {args.seed}).")
            sampled_data = random.sample(all_data, args.random)
            
            # Create a temporary input file for the sampled data
            sampled_input_file = f"input_sampled_{args.seed}_{args.random}.json"
            with open(sampled_input_file, 'w') as f:
                json.dump(sampled_data, f, indent=2, ensure_ascii=False)
            
            current_input = sampled_input_file
            # We don't need to pass random to run_distributed_logic anymore since we filtered the input
            args.random = 0 

    # 1. Initial Run
    if args.resume and os.path.exists(final_output):
        print(f"Resuming from existing output: {final_output}")
        shutil.copy(final_output, temp_run_output)
    else:
        print("\n>>> Phase 1: Initial Execution")
        success = run_distributed_logic(current_input, temp_run_output, args.workers, log_dir, 0, args.seed)
        if not success:
            print("Execution interrupted. Proceeding to next phase with partial results...")
            # return  <-- Removed return to allow proceeding

    # Evaluate Phase 1
    if gt_map:
        current_data = load_jsonl(temp_run_output)
        acc, corr, tot = calculate_accuracy(current_data, gt_map)
        print(f"Phase 1 Accuracy: {acc:.2%} ({corr}/{tot})")

    # 2. Retry Loop (Rounds & Retries)
    retry_dir = "retry_tasks"
    if os.path.exists(retry_dir): shutil.rmtree(retry_dir)
    os.makedirs(retry_dir, exist_ok=True)

    for round_idx in range(args.rounds):
        print(f"\n=== Round {round_idx+1}/{args.rounds} ===")
        
        # --- Inner Loop: Format Retries ---
        for retry_idx in range(args.retries):
            format_errors, wrong_answers, stats = scan_for_errors(temp_run_output, current_input, gt_map if args.groundtruth else None)
            
            if not format_errors:
                print("  Format check passed.")
                break
                
            print(f"  [Format Retry {retry_idx+1}/{args.retries}] Found {len(format_errors)} format errors (Missing: {stats['missing']}, Invalid: {stats['format']}). Retrying...")
            
            # Clean logs for failed cases
            clean_logs(log_dir, format_errors)
            
            retest_input = os.path.join(retry_dir, f"input_round_{round_idx+1}_retry_{retry_idx+1}.json")
            retest_output = os.path.join(retry_dir, f"output_round_{round_idx+1}_retry_{retry_idx+1}.jsonl")
            
            with open(retest_input, 'w') as f:
                json.dump(format_errors, f, indent=2, ensure_ascii=False)
                
            success = run_distributed_logic(retest_input, retest_output, args.workers, log_dir, 0, args.seed)
            
            # Merge updates
            base_data = load_jsonl(temp_run_output)
            new_data = load_jsonl(retest_output)
            base_data.update(new_data)
            
            with open(temp_run_output, 'w') as f:
                for item in base_data.values():
                    f.write(json.dumps(item, ensure_ascii=False) + '\n')

        # --- End of Round Check: Oracle ---
        format_errors, wrong_answers, stats = scan_for_errors(temp_run_output, current_input, gt_map if args.groundtruth else None)
        
        if format_errors:
             print(f"  Warning: Still have {len(format_errors)} format errors after retries.")
        
        if not wrong_answers and not format_errors:
            print("  >>> All answers correct! (or no GT)")
            break
            
        if round_idx < args.rounds - 1:
            print(f"  >>> Found {len(wrong_answers)} wrong answers and {len(format_errors)} format errors. Starting next round...")
            
            # Prepare input for next round (wrong cases + remaining format errors)
            next_round_cases = wrong_answers + format_errors
            
            # Clean logs for these cases
            clean_logs(log_dir, next_round_cases)
            
            # Update current_input for the next round to only focus on these cases
            current_input = os.path.join(retry_dir, f"input_round_{round_idx+2}.json")
            with open(current_input, 'w') as f:
                json.dump(next_round_cases, f, indent=2, ensure_ascii=False)
                
            # Run the next round's initial execution (which is effectively the first "retry" of the new round)
            # Actually, we can just let the next iteration's "Format Retry" loop handle it?
            # No, the format retry loop expects to fix format errors.
            # Wrong answers are syntactically correct but semantically wrong.
            # We need to run them once to generate new answers.
            
            print(f"  Running {len(next_round_cases)} cases for Round {round_idx+2}...")
            round_output = os.path.join(retry_dir, f"output_round_{round_idx+2}.jsonl")
            success = run_distributed_logic(current_input, round_output, args.workers, log_dir, 0, args.seed)
            
            # Merge updates
            base_data = load_jsonl(temp_run_output)
            new_data = load_jsonl(round_output)
            base_data.update(new_data)
            
            with open(temp_run_output, 'w') as f:
                for item in base_data.values():
                    f.write(json.dumps(item, ensure_ascii=False) + '\n')
                    
            # Evaluate
            if gt_map:
                acc, corr, tot = calculate_accuracy(base_data, gt_map)
                print(f"  Round {round_idx+2} Accuracy: {acc:.2%} ({corr}/{tot})")
        else:
            print(f"  >>> Max rounds reached. Remaining wrong answers: {len(wrong_answers)}")
            
        # Cleanup retest files (Optional)
        # ...

    # 3. Finalize
    print(f"\n>>> Finalizing output to {final_output}")
    final_data = load_jsonl(temp_run_output)
    
    # Sort by input order if possible
    try:
        with open(current_input, 'r') as f:
            input_order = [x['uuid'] for x in json.load(f) if 'uuid' in x]
            ordered_items = []
            for uid in input_order:
                if uid in final_data:
                    item = final_data[uid]
                    if 'run_id' in item: del item['run_id']
                    ordered_items.append(item)
            
            # Add any remaining that weren't in input (shouldn't happen but safe)
            for uid, item in final_data.items():
                if uid not in input_order:
                    if 'run_id' in item: del item['run_id']
                    ordered_items.append(item)
            
            final_items = ordered_items
    except:
        final_items = list(final_data.values())
        for item in final_items:
            if 'run_id' in item: del item['run_id']

    with open(final_output, 'w') as f:
        for item in final_items:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    if os.path.exists(temp_run_output):
        os.remove(temp_run_output)
        
    # Cleanup sampled input file if it exists
    if current_input != args.input and os.path.exists(current_input):
        os.remove(current_input)
        
    print("Done.")

def cmd_compare(args):
    """Compare current results with baseline/GT"""
    if not os.path.exists(args.current):
        print(f"Error: Current file {args.current} not found.")
        return
        
    current = load_jsonl(args.current)
    baseline = load_jsonl(args.baseline) if args.baseline else {}
    
    # Load GT for accuracy calculation
    gt_map = {}
    if args.groundtruth and os.path.exists(args.groundtruth):
        with open(args.groundtruth, 'r') as f:
            try:
                content = f.read().strip()
                if content.startswith('['):
                    for x in json.loads(content):
                        if 'uuid' in x: gt_map[x['uuid']] = x
                else:
                    for line in content.split('\n'):
                        if line.strip():
                            x = json.loads(line)
                            if 'uuid' in x: gt_map[x['uuid']] = x
            except:
                pass
    
    if not gt_map:
        print("Warning: No Ground Truth file provided or found. Cannot calculate accuracy improvement.")
        # Fallback to simple diff if no GT
        if baseline:
            diffs = []
            for uid, item in current.items():
                if uid in baseline:
                    curr_comp = item.get('component', '').strip()
                    base_comp = baseline[uid].get('component', '').strip()
                    if curr_comp != base_comp:
                        diffs.append((uid, base_comp, curr_comp))
            print(f"Found {len(diffs)} differences between current and baseline.")
        return

    print(f"Comparing Current ({len(current)}) vs Baseline ({len(baseline)}) against GT...")
    
    # Calculate Current Accuracy
    curr_acc, curr_corr, curr_tot = calculate_accuracy(current, gt_map)
    print(f"Current Accuracy:  {curr_acc:.2%} ({curr_corr}/{curr_tot})")
    
    # Calculate Baseline Accuracy
    base_acc, base_corr, base_tot = calculate_accuracy(baseline, gt_map)
    print(f"Baseline Accuracy: {base_acc:.2%} ({base_corr}/{base_tot})")
    
    # Show Improvement
    improvement = curr_acc - base_acc
    print(f"Improvement:       {improvement:+.2%}")

    # Identify Failed Cases in Current (for next input)
    failed_uuids = set()
    for uid in gt_map:
        # Check if missing or wrong in current
        if uid not in current:
            failed_uuids.add(uid)
        else:
            gt_inst = normalize_instance(gt_map[uid].get('instance', ''))
            pred = current[uid].get('component', '').strip()
            is_invalid = not pred or pred.upper() == "TODO" or pred == "" or pred not in VALID_COMPONENTS
            if is_invalid or pred not in gt_inst:
                failed_uuids.add(uid)

    print(f"Failed/Missing Cases in Current: {len(failed_uuids)}")

    # Generate Next Input File
    if args.next_input:
        if not args.input_source:
            print("Error: --input-source is required to generate next input file.")
            return
            
        if not os.path.exists(args.input_source):
            print(f"Error: Input source {args.input_source} not found.")
            return
            
        retest_cases = []
        with open(args.input_source, 'r') as f:
            all_cases = json.load(f)
            for case in all_cases:
                if case.get("uuid") in failed_uuids:
                    retest_cases.append(case)
        
        with open(args.next_input, 'w') as f:
            json.dump(retest_cases, f, indent=2, ensure_ascii=False)
        print(f"Saved {len(retest_cases)} failed cases to {args.next_input}")

def main():
    parser = argparse.ArgumentParser(description="Context-RCA Manager Tool")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # 1. RUN (Smart)
    p_run = subparsers.add_parser("run", help="One-click Run & Fix")
    p_run.add_argument("--input", required=True, help="Input JSON file")
    p_run.add_argument("--output", required=True, help="Final Output JSONL file")
    p_run.add_argument("--workers", type=int, default=10, help="Parallel workers")
    p_run.add_argument("--rounds", type=int, default=1, help="Max rounds for GT correction (Outer Loop)")
    p_run.add_argument("--retries", type=int, default=3, help="Max retries for format errors (Inner Loop)")
    p_run.add_argument("--random", type=int, default=0, help="Randomly sample N items to run (0 for all)")
    p_run.add_argument("--seed", type=int, default=42, help="Random seed for sampling (default: 42)")
    p_run.add_argument("--log-dir", default="logs", help="Log directory (will be overwritten)")
    p_run.add_argument("--groundtruth", default="output/groundtruth.jsonl", help="GT file for Oracle Retry (default: output/groundtruth.jsonl)")
    p_run.add_argument("--resume", action="store_true", help="Resume from existing output file (skip Phase 1)")
    p_run.set_defaults(func=cmd_run)

    # 2. COMPARE
    p_comp = subparsers.add_parser("compare", help="Compare results")
    p_comp.add_argument("--current", required=True, help="Current result file")
    p_comp.add_argument("--baseline", required=True, help="Previous result file")
    p_comp.add_argument("--groundtruth", default="output/groundtruth.jsonl", help="GT file for accuracy calc")
    p_comp.add_argument("--next-input", help="Output file for failed cases (JSON)")
    p_comp.add_argument("--input-source", default="input/input.json", help="Original input JSON (needed for next input)")
    p_comp.set_defaults(func=cmd_compare)

    args = parser.parse_args()
    if hasattr(args, 'func'):
        args.func(args)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
